# Generated by Django 4.0.3 on 2022-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_content', models.TextField(default='')),
                ('isModelLog', models.BooleanField(default=True)),
                ('model_logged', models.CharField(default='', max_length=1024)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
