# Generated by Django 4.0.3 on 2022-03-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botname', models.CharField(max_length=1024)),
                ('Labels', models.JSONField(null=True)),
                ('intents', models.JSONField(null=True)),
            ],
        ),
    ]
