# Generated by Django 4.0.3 on 2022-04-16 13:32

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fakate', '0002_rename_labels_bottrainingdata_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottrainingdata',
            name='model',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bottrainingdata',
            name='botname',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
