# Generated by Django 4.0.3 on 2022-04-16 13:50

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fakate', '0003_bottrainingdata_model_alter_bottrainingdata_botname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottrainingdata',
            name='vectorizer',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
