# Generated by Django 4.0.3 on 2022-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakate', '0004_bottrainingdata_vectorizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottrainingdata',
            name='intents',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='bottrainingdata',
            name='labels',
            field=models.JSONField(default={}),
        ),
    ]
