# Generated by Django 4.0.3 on 2022-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakate', '0005_alter_bottrainingdata_intents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottrainingdata',
            name='intents',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bottrainingdata',
            name='labels',
            field=models.JSONField(default=dict),
        ),
    ]
