# Generated by Django 3.2.8 on 2021-10-17 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_packagefeatures_service_servicepackage_serviceuser_serviceusersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to='users.service', verbose_name='service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_key',
            field=models.UUIDField(default=uuid.UUID('a12c8379-8ec0-4dce-82b0-fa6e770c9ba4')),
        ),
    ]
