# Generated by Django 3.2.8 on 2021-11-13 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211017_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_key',
            field=models.UUIDField(default=uuid.UUID('2e9ebbba-3ff9-4670-a7d0-9b3599b4e94c')),
        ),
    ]
