# Generated by Django 3.2.8 on 2021-11-13 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211113_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsapair',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsapair',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_key',
            field=models.UUIDField(default=uuid.UUID('fee4b3e4-4f44-454a-82a0-b6fdcf5c0c20')),
        ),
    ]
