# Generated by Django 3.2.8 on 2021-11-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211113_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_key',
            field=models.CharField(default='8z@4@ms%e47_rwf)*_%9m85v3uiwd@%7_u20c#a!0hvna4qa0i', max_length=1024),
        ),
    ]
