# Generated by Django 3.2.8 on 2021-11-24 02:04

import django.core.management.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_service_service_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_key',
            field=models.CharField(default=django.core.management.utils.get_random_secret_key, max_length=1024),
        ),
    ]
