# Generated by Django 3.2.8 on 2021-12-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_service_service_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicemailconfiguration',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
