# Generated by Django 3.2.8 on 2021-12-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_dynamicemailconfiguration_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicemailconfiguration',
            name='api_key',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
