# Generated by Django 3.2.8 on 2022-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_dynamicemailconfiguration_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_content', models.TextField(default='')),
                ('isModelLog', models.BooleanField(default=True)),
                ('model_logged', models.CharField(default='', max_length=1024)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='rsapair',
            name='password',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
