# Generated by Django 3.2.8 on 2022-03-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220305_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicemailconfiguration',
            old_name='api_key',
            new_name='email_key',
        ),
    ]
