# Generated by Django 4.0.3 on 2022-03-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_name', models.CharField(max_length=1024)),
                ('twilio_account_sid', models.CharField(max_length=1024)),
                ('twilio_auth_token', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='smsbot.twilioaccountsettings')),
            ],
        ),
    ]
