# Generated by Django 4.0.3 on 2022-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_dynamicemailconfiguration_email_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_key',
            field=models.CharField(default='mFd1a6bo4i4d', max_length=1024),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='name',
            field=models.CharField(default='qFhG4HH83AjD', max_length=256, verbose_name='email unique name'),
        ),
    ]
