# Generated by Django 4.0.3 on 2022-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_dynamicemailconfiguration_email_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_key',
            field=models.CharField(default='jj1mDdAbp28D', max_length=1024),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='name',
            field=models.CharField(default='bmphA4Fkkca3', max_length=256, verbose_name='email unique name'),
        ),
    ]
