# Generated by Django 4.0.3 on 2022-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_dynamicemailconfiguration_email_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_key',
            field=models.CharField(default='fq99pD8Gb9qF', max_length=1024),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='name',
            field=models.CharField(default='27q2lhD9Ig1G', max_length=256, verbose_name='email unique name'),
        ),
    ]
