# Generated by Django 4.0.3 on 2022-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_dynamicemailconfiguration_email_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_key',
            field=models.CharField(default='m1HD37E7cA9g', max_length=1024),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='name',
            field=models.CharField(default='e2qf59eDfqm4', max_length=256, verbose_name='email unique name'),
        ),
    ]
