name: Docker Image CI publish and deploy a test.


# variables
# main --> the watched brach
# auth --> the name of the project

on:
  release:
    type: 
      - "released"
  pull_request:
    branches:
      - "main"

jobs:

  build-publish-deploy:
    name: build and push docker
    runs-on: ubuntu-latest
    steps:

    - name: checkout to main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/auth:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/auth:latest
        cache-to: type=inline


    # - name: Build
    #   run: |
    #     chmod +x build.sh
    #     ./build.sh prod

    # - name: push Image
    #   run: |
    #     sudo docker images
    #     sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    #     sudo docker push ${{ secrets.DOCKER_USERNAME }}/auth:latest